export interface Vehicle {
  id: string
  name: string
  category: "Sedan" | "SUV" | "Hatchback" | "Esportivo" | "Cupê"
  year: number
  images: string[]
  pricePerDay: number
  transmission: "Automático" | "Manual"
  passengers: number
  fuel: "Flex" | "Gasolina" | "Diesel"
  doors: number
  airConditioning: boolean
  available: boolean
  description: string
  features: string[]
}

export const vehicles: Record<string, Vehicle> = {
  "1": {
    id: "1",
    name: "Toyota Corolla",
    category: "Sedan",
    year: 2024,
    images: [
      "/cars/toyota-corolla-1.jpg",
      "/cars/toyota-corolla-2.jpg",
      "/cars/toyota-corolla-3.jpg",
      "/cars/toyota-corolla-4.jpg",
    ],
    pricePerDay: 180,
    transmission: "Automático",
    passengers: 5,
    fuel: "Flex",
    doors: 4,
    airConditioning: true,
    available: true,
    description:
      "O Toyota Corolla 2024 é um sedan confiável e sofisticado, perfeito para viagens longas ou uso executivo. Destaca-se pelo design moderno com nova grade frontal em preto piano, faróis full LED com assistência automática de facho alto e tecnologia avançada com central multimídia de 12,3 polegadas.",
    features: [
      "Ar-condicionado automático dual zone",
      "Direção elétrica progressiva",
      "Vidros elétricos com one touch",
      "Travas elétricas com travamento automático",
      "Central multimídia 12,3\" com Android Auto e Apple CarPlay",
      "Cluster digital TFT 12,3\"",
      "Bluetooth e USB",
      "Câmera de ré com visão 360°",
      "Sensor de estacionamento frontal e traseiro",
      "8 Airbags",
      "ABS com EBD",
      "Controle de estabilidade e tração",
      "Faróis full LED com DRL",
      "Rodas de liga leve 17\"",
      "Bancos em couro",
      "Piloto automático adaptativo",
    ],
  },
  "2": {
    id: "2",
    name: "Honda HR-V",
    category: "SUV",
    year: 2024,
    images: [
      "/cars/honda-hrv-1.jpg",
      "/cars/honda-hrv-2.jpg",
      "/cars/honda-hrv-3.jpg",
      "/cars/honda-hrv-4.jpg",
    ],
    pricePerDay: 250,
    transmission: "Automático",
    passengers: 5,
    fuel: "Flex",
    doors: 4,
    airConditioning: true,
    available: true,
    description:
      "O Honda HR-V 2024 combina design arrojado com tecnologia de ponta. SUV compacto com visual de cupê, oferece amplo espaço interno graças ao sistema de bancos Magic Seat, faróis full LED e central multimídia moderna. Ideal para quem busca versatilidade e conforto.",
    features: [
      "Ar-condicionado automático digital",
      "Direção elétrica",
      "Vidros elétricos",
      "Travas elétricas",
      "Central multimídia touchscreen 8\"",
      "Android Auto e Apple CarPlay sem fio",
      "Painel digital 7\"",
      "Bluetooth",
      "Câmera de ré multi-ângulo",
      "Sensor de estacionamento traseiro",
      "6 Airbags",
      "ABS com EBD",
      "Controle de estabilidade VSA",
      "Assistente de partida em rampa",
      "Faróis full LED",
      "Rodas de liga leve 17\"",
      "Banco do motorista com ajuste elétrico",
      "Sistema Magic Seat (bancos reconfiguráveis)",
    ],
  },
  "3": {
    id: "3",
    name: "Chevrolet Onix",
    category: "Hatchback",
    year: 2024,
    images: [
      "/cars/chevrolet-onix-1.jpg",
      "/cars/chevrolet-onix-2.jpg",
      "/cars/chevrolet-onix-3.jpg",
      "/cars/chevrolet-onix-4.jpg",
    ],
    pricePerDay: 120,
    transmission: "Manual",
    passengers: 5,
    fuel: "Flex",
    doors: 4,
    airConditioning: true,
    available: true,
    description:
      "O Chevrolet Onix 2024 é o hatchback mais vendido do Brasil. Com design moderno e grade frontal unificada aos faróis, oferece excelente custo-benefício. Motor 1.0 econômico, ideal para uso urbano e viagens curtas com baixo consumo de combustível.",
    features: [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos dianteiros",
      "Travas elétricas",
      "Central multimídia MyLink 8\" touchscreen",
      "Android Auto e Apple CarPlay",
      "Bluetooth",
      "Câmera de ré",
      "Computador de bordo",
      "2 Airbags",
      "ABS com EBD",
      "Controle de estabilidade e tração",
      "Faróis com máscara negra",
      "Rodas de aço 15\" com calotas",
      "Volante multifuncional",
      "Alarme",
    ],
  },
  "4": {
    id: "4",
    name: "Chevrolet Camaro SS",
    category: "Esportivo",
    year: 2024,
    images: [
      "/cars/chevrolet-camaro-1.jpg",
      "/cars/chevrolet-camaro-2.jpg",
      "/cars/chevrolet-camaro-3.jpg",
      "/cars/chevrolet-camaro-4.jpg",
    ],
    pricePerDay: 650,
    transmission: "Automático",
    passengers: 2,
    fuel: "Gasolina",
    doors: 2,
    airConditioning: true,
    available: true,
    description:
      "O Chevrolet Camaro SS 2024 é um ícone muscle car americano com design agressivo e performance brutal. Equipado com motor V8 6.2 de 461 cv e 62,9 kgfm de torque, acelera de 0-100 km/h em apenas 4,2 segundos. Transmissão automática de 10 velocidades e velocidade máxima de 290 km/h. Cupê esportivo 2+2 lugares (bancos traseiros limitados).",
    features: [
      "Ar-condicionado automático dual zone",
      "Direção elétrica com assistência variável",
      "Vidros elétricos",
      "Travas elétricas",
      "Central multimídia com tela touchscreen",
      "Android Auto e Apple CarPlay",
      "Bluetooth e Wi-Fi nativo",
      "Sistema de áudio premium",
      "Câmera de ré",
      "Sensores de estacionamento",
      "6 Airbags",
      "ABS com EBD",
      "Controle de estabilidade e tração",
      "4 modos de condução (Passeio, Esporte, Pista, Neve)",
      "Faróis LED com DRL",
      "Rodas de liga leve esportivas 20\"",
      "Bancos esportivos em couro",
      "Volante esportivo multifuncional",
    ],
  },
  "5": {
    id: "5",
    name: "Hyundai HB20",
    category: "Hatchback",
    year: 2023,
    images: [
      "/cars/hyundai-hb20-1.jpg",
      "/cars/hyundai-hb20-2.jpg",
      "/cars/hyundai-hb20-3.jpg",
      "/cars/hyundai-hb20-4.jpg",
    ],
    pricePerDay: 130,
    transmission: "Manual",
    passengers: 5,
    fuel: "Flex",
    doors: 4,
    airConditioning: true,
    available: true,
    description:
      "O Hyundai HB20 2023 renovado traz design mais moderno com faróis finos integrados à grade frontal e lanternas traseiras redesenhadas inspiradas no Tucson. Hatchback compacto econômico, ideal para uso diário na cidade com boa dirigibilidade e conforto.",
    features: [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos dianteiros",
      "Travas elétricas",
      "Central multimídia Bluelink 8\" touchscreen",
      "Android Auto e Apple CarPlay",
      "Bluetooth",
      "Câmera de ré",
      "Computador de bordo",
      "2 Airbags",
      "ABS com EBD",
      "Controle de estabilidade ESC",
      "Faróis com projetor",
      "Lanternas em LED",
      "Rodas de aço 15\" com calotas",
      "Volante multifuncional",
    ],
  },
  "6": {
    id: "6",
    name: "Jeep Compass",
    category: "SUV",
    year: 2024,
    images: [
      "/cars/jeep-compass-1.jpg",
      "/cars/jeep-compass-2.jpg",
      "/cars/jeep-compass-3.jpg",
      "/cars/jeep-compass-4.jpg",
    ],
    pricePerDay: 320,
    transmission: "Automático",
    passengers: 5,
    fuel: "Flex",
    doors: 4,
    airConditioning: true,
    available: false,
    description:
      "O Jeep Compass 2024 é o SUV médio mais tecnológico do segmento. Com design icônico, grade de sete fendas, faróis full LED e interior premium. Disponível com motor turbo flex ou turbodiesel. Oferece capacidade off-road com tração 4x4 e sistema Selec-Terrain para diferentes tipos de terreno.",
    features: [
      "Ar-condicionado automático dual zone",
      "Direção elétrica",
      "Vidros elétricos com one touch",
      "Travas elétricas",
      "Central multimídia Uconnect 10,1\" touchscreen",
      "Painel digital customizável 10,25\"",
      "Android Auto e Apple CarPlay sem fio",
      "Carregamento wireless",
      "Bluetooth",
      "Câmera de ré com park assist",
      "Sensores de estacionamento 360°",
      "7 Airbags",
      "ABS com EBD",
      "Controle de estabilidade e tração",
      "Sistema Selec-Terrain (tração 4x4)",
      "Faróis full LED bi-xenon",
      "Rodas de liga leve 18\"",
      "Teto solar panorâmico",
      "Bancos em couro",
      "Controle de cruzeiro adaptativo",
    ],
  },
  "7": {
    id: "7",
    name: "Audi A5",
    category: "Cupê",
    year: 2026,
    images: [
      "/cars/audi-a5-1.jpg",
      "/cars/audi-a5-2.jpg",
      "/cars/audi-a5-3.jpg",
      "/cars/audi-a5-4.jpg",
    ],
    pricePerDay: 450,
    transmission: "Automático",
    passengers: 5,
    fuel: "Gasolina",
    doors: 4,
    airConditioning: true,
    available: true,
    description:
      "O Audi A5 Sportback 2025 é um cupê de quatro portas que combina elegância, sofisticação e tecnologia alemã. Motor 2.0 TFSI turbo de 204 cv e 32,6 kgfm de torque, com transmissão S tronic de 7 velocidades e tração Quattro integral. Acelera de 0-100 km/h em 6,8 segundos. Design refinado com linhas esportivas e acabamento premium.",
    features: [
      "Ar-condicionado automático dual zone",
      "Direção elétrica progressiva",
      "Vidros elétricos com one touch",
      "Travas elétricas com travamento automático",
      "Central multimídia MMI touchscreen com navegação",
      "Painel digital Audi Virtual Cockpit 12,3\"",
      "Android Auto e Apple CarPlay sem fio",
      "Bluetooth e USB-C",
      "Câmera de ré com linhas dinâmicas",
      "Sensores de estacionamento 360°",
      "6 Airbags",
      "ABS com EBD",
      "Controle de estabilidade ESC",
      "Tração integral Quattro permanente",
      "Faróis full LED Matrix com assinatura luminosa",
      "Rodas de liga leve S Line 20\"",
      "Bancos esportivos em couro com ajuste elétrico",
      "Volante multifuncional esportivo em couro",
    ],
  },
  "8": {
    id: "8",
    name: "Nissan Kicks",
    category: "SUV",
    year: 2024,
    images: [
      "/cars/nissan-kicks-1.jpg",
      "/cars/nissan-kicks-2.jpg",
      "/cars/nissan-kicks-3.jpg",
      "/cars/nissan-kicks-4.jpg",
    ],
    pricePerDay: 260,
    transmission: "Automático",
    passengers: 5,
    fuel: "Flex",
    doors: 4,
    airConditioning: true,
    available: true,
    description:
      "O Nissan Kicks 2024 é um SUV compacto inovador com design diferenciado e lanternas em formato boomerang. Destaca-se pelo amplo porta-malas, tecnologia Nissan Safety Shield com assistentes de condução e interior espaçoso. Motor 1.6 flex com câmbio CVT garante boa economia e conforto.",
    features: [
      "Ar-condicionado automático digital",
      "Direção elétrica",
      "Vidros elétricos com one touch",
      "Travas elétricas",
      "Central multimídia 8\" touchscreen",
      "Painel digital 7\" customizável",
      "Android Auto e Apple CarPlay",
      "Bluetooth",
      "Câmera de ré 360°",
      "Sensor de estacionamento traseiro",
      "6 Airbags",
      "ABS com EBD",
      "Controle de estabilidade VDC",
      "Assistente de partida em rampa",
      "Faróis full LED com DRL",
      "Lanternas LED em formato boomerang",
      "Rodas de liga leve 17\"",
      "Volante multifuncional em couro",
      "Sistema Nissan Safety Shield",
    ],
  },
}

export function getVehicle(id: string): Vehicle | undefined {
  return vehicles[id]
}

export function getAllVehicles(): Vehicle[] {
  return Object.values(vehicles)
}

export function getAvailableVehicles(): Vehicle[] {
  return getAllVehicles().filter((vehicle) => vehicle.available)
}
